src/main_project/urls.py
from django.urls import path, include
from main_project.views import home, team, report, \
							graphy, choose_bam_file, graphing_dashboard

urlpatterns = [
    	path('', home, name='home'),
    	path('team', team, name='team'),
    	path('report', report, name='report'),
    	path('graphy', graphy, name='graphy'),
    	path('choose_bam_file', choose_bam_file, name='choose_bam_file'),
    	path('graphing_dashboard/', graphing_dashboard, name='graphing_dashboard'),
]

src/thagomizer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include(('main_project.urls', 'main_project'), namespace='main_project')),
    
]

src/main_project/views.py
import pandas as pd
import itertools
import sys
import os
import spectra
from io import StringIO
import random
import main_project.graphy.clip_tools as ct
from main_project.graphy.functions import *

from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import json
from django.core.mail import EmailMultiAlternatives






path_to_static = settings.PATH_TO_STATIC + '/graphy_static/'

def home(request):

	return render(request, 'main_project/home.html')

def team(request):
	return render(request, 'main_project/team.html')

def report(request):
	if request.method == 'POST':
		try:
			subject, from_email, to = 'Thagomizer Report', settings.SEND_EMAIL_TO, settings.SEND_EMAIL_FROM
			text_content = 'Report about Thagomizer.' 
			html_content = "<h3>You got a new report from:" + request.POST['name'] + \
            		"</h3></br><h5	>Email: "+request.POST['email']+ \
			                    		"</h5></br><p>Message "+request.POST['message']
			to = str(to)
			msg = EmailMultiAlternatives(subject, text_content, from_email, [to,])
			msg.attach_alternative(html_content, "text/html")
			msg.send()
		except Exception as e:
			print('Error ', e)
			pass

	return render(request, 'main_project/report.html')

def choose_bam_file(request):
	return render(request, 'main_project/choose_bam_file.html')	


def graphing_dashboard(request):

	genome = request.GET.get('genome', False)
	bam_files = request.GET.getlist('files[]')

	if genome is False or len(bam_files) < 1:
		return redirect('main_project:choose_bam_file')

	try:

		data_file_mm10 = []
		data_file_hg19 = []

		data_file_mm10_loc = settings.PATH_TO_STATIC + '/graphy_static/Data/mm10'
		data_file_hg19_loc = settings.PATH_TO_STATIC + '/graphy_static/Data/hg19'

		for i in os.listdir(data_file_mm10_loc):
			file_type = i[-3]+i[-2]+i[-1]
			if file_type=='bam':
				data_file_mm10.append(i)

		for i in os.listdir(data_file_hg19_loc):
			file_type = i[-3]+i[-2]+i[-1]
			if file_type=='bam':
				data_file_hg19.append(i)



	except:
		data_file_mm10 = ''
		data_file_hg19 = ''



	file_targetscan = path_to_static + "Genome_Data/Targetscan7_fixed.bed"

	def get_target_scan(target_scan_file):
		beddb = pd.read_table(target_scan_file,names=["chrom", "start", "stop", "miRNA"], usecols=[0,1,2,3])
		families = beddb.miRNA.unique()
		f = families.tolist()
		return sorted(f[1:])

	options_list = get_target_scan(file_targetscan)

	# print(options_list)
	
	context = {
		'genome': genome,
		'bam_files': bam_files,
		'options_list': options_list,
		'data_file_mm10': data_file_mm10,
		'data_file_hg19': data_file_hg19
	}
	return render(request, 'main_project/graphing_dashboard.html', context)

def graphy(request):

	path_to_static = settings.PATH_TO_STATIC + '/graphy_static/'


	file_utr3 = path_to_static + "Genome_Data/refseq_3utr.bed"
	file_refseq = path_to_static + "Genome_Data/refseq_names.txt"
	file_targetscan = path_to_static + "Genome_Data/Targetscan7_fixed.bed"
	file_refgenebed = path_to_static + "Genome_Data/refGene.bed"
	default_track_folder = path_to_static + "Data/"
	# Placeholder defaults
	placeholder_file_bedfile = path_to_static + "Genome_Data/RK53/mmu-miR-29a-3p.bed"

	def run(figwidth, color_values, track_names, track_type, bedtrack, bedfile, bedtype, name,annotate_bed, geneid, chrom,start, stop, refseqid, strand, bigwignames, fontsize, shade_by_bed):
# 	############# Constant Values ############# Do not edit

	    # staticaxes = True
	    # LeftToRight = False
	    # axis_off = False
	    # refseqtrack = True

		staticaxes = True 										
		if request.GET['staticaxes'] == "true":
			staticaxes = True
		elif request.GET['staticaxes'] == "false":
			staticaxes = False


		LeftToRight = False 										
		if request.GET['LeftToRight'] == "true":
			LeftToRight = True
		elif request.GET['LeftToRight'] == "false":
			LeftToRight = False


		axis_off = False 										
		if request.GET['axis_off'] == "true":
			axis_off = True
		elif request.GET['axis_off'] == "false":
			axis_off = False


		refseqtrack = True 										
		if request.GET['refseqtrack'] == "true":
			refseqtrack = True
		elif request.GET['refseqtrack'] == "false":
			refseqtrack = False



		figheight = float(figwidth/4.0)
		shade = itertools.cycle(color_values)
		colors = itertools.cycle([spectra.html(i).darken(20).hexcode for i in color_values])
		limits = [start, stop]
		staggerbed = True
		output_folder = path_to_static + "../Output/"
		outputformat = "png"
		outputsuffix = "" + str(random.randint(1,1019080210))
		dpi = float(300.0)
		legend = True
		static_url = staticfiles_storage.url('graphy_static/')
		# track_files = ['Data' + f for f in track_names]
		track_files = [static_url + f for f in track_names]
		bigwigfiles = ['Data' + f for f in bigwignames]
		wig_df_list = get_wig_data(bigwigfiles,bigwignames,chrom,start,stop)
		depths = get_depth_data(track_files,track_names,chrom,start,stop,strand,track_type)

# 	    ############# Constant Values #############

		plot_value = plot(figwidth,figheight,refseqtrack,LeftToRight,strand,depths,
		   					colors,shade,limits,bedtrack,start,stop,staggerbed,bigwignames,
		    				wig_df_list,shade_by_bed,output_folder,geneid,outputsuffix,outputformat,dpi,track_names,axis_off,
		   					legend,staticaxes,bedfile,bedtype,name,chrom,refseqid,annotate_bed,fontsize)






		"""
		to convert this

			values = {
				'GCliPP_everything.bam': {
						142903034: 0, 
						142903035: 0, 
						142906866: 0
					},
				 'miR29_WT_Th17.bam': {
				 		142903034: 0,
				 		142903035: 0,
				 		142906866: 0
				 	}
			}

		into this
			[
				
				{
				"year": "142903035",
				"GCliPP_everything": 1,
				"miR29_WT_Th17": 0
				}, {
				"year": "142903035",
				"GCliPP_everything": 1,
				"miR29_WT_Th17": 0
				}


			]
		"""

		real_value = []
		bam_files = []
		for value in plot_value:
			bam_files.append(value)


		for bam_file in bam_files:
			this_bam_file_index = bam_files.index(bam_file)
			if this_bam_file_index==0:
				values_of_this_bam = plot_value[bam_file]
				
				for this_val in values_of_this_bam:
					first_dict_val = this_val
					break;

				for val in values_of_this_bam:
					# print('val', val)
					
					real_value.append({
							# 'x_axis': values_of_this_bam[val],
							bam_file: values_of_this_bam[val],
							'year': str((val+100)-first_dict_val)	#our charts doesn't support less than 3 digit or more than 6 digit
							# 'year': str(val)	#our charts doesn't support less than 3 digit or more than 6 digit
						})

				
			else:
				values_of_this_bam = plot_value[bam_file]
				
				for ind, val2 in enumerate(values_of_this_bam):
					this_index = ind
					real_value[this_index][bam_file] = values_of_this_bam[val2]
			

		# print(real_value)
		csv_url = '/static/CSV_Output/'+geneid+outputsuffix+'.csv'
		pdf_url = '/static/Output/'+geneid+outputsuffix+'.pdf'
		outputsuffix = 'static/Output/'+geneid+outputsuffix+'.png'

		return {
			'bam_files': bam_files,
			'image_url': outputsuffix,
			'pdf_url': pdf_url,
			'csv_url': csv_url,
			'graph_data': real_value,
			'label_data': plot_value.get('label_data', {}),
			'first_dict_val': first_dict_val 	#for converting date to number in labeling need to use in js
		}
			

	# print(request.GET)
	try:
		# print(request.GET)
		# print('ata')
		figwidth = int(request.GET['figwidth'])						#working
		color_values = request.GET.getlist('color_values[]')  	#working
		track_names = request.GET.getlist('track_names[]')		#working
		track_type = request.GET.getlist('track_type[]')		#working

		bedtrack = False 										#working
		if request.GET['bedtrack'] == "true":
			bedtrack = True
		elif request.GET['bedtrack'] == "false":
			bedtrack = False

		
		bedfile = path_to_static+request.GET['bedfile']			#working
		if bedfile=='':
			bedfile = None

		bedtype = request.GET['bedtype'] 						#working
		if bedtype=='':
			bedtype = None

		# print('name is', request.GET['name'])
		name = request.GET['name']								#working
		if name=='':
			name = None

		annotate_bed = True 									#working
		if request.GET['annotate_bed'] == "true":
			annotate_bed = True
		elif request.GET['annotate_bed'] == "false":
			annotate_bed = False


		geneid = request.GET['geneid']
		chrom = request.GET['chrom']
		start = int(request.GET['start'])
		stop = int(request.GET['stop'])
		refseqid = request.GET['refseqid']
		strand = request.GET['strand']
		bigwignames = request.GET.getlist('bigwignames[]')
		fontsize = int(request.GET['fontsize'])
		shade_by_bed = False 									#working
		if request.GET['shade_by_bed'] == "true":
			shade_by_bed = True
		elif request.GET['shade_by_bed'] == "false":
			shade_by_bed = False



		# figwidth = 35.0				#working
		# color_values = ['#ea3a3a']		#working
		# track_names = ["GCliPP_cd8_merged.bam"]		#working
		# track_type = ["s"]		#working

		# bedtrack = False 			#working
		# bedfile = None 			#working
		# bedtype = None			#working
		# name = None				#working
		# annotate_bed = True 	    #working
		# geneid = 'Actb'
		# chrom = 'chr5'
		# start = 142903034			#working
		# stop = 142906867			#working
		# refseqid = 'NM_007393'
		# strand = '-'
		# bigwignames = []
		# fontsize = 20.0			#working
		# shade_by_bed = False

		image_name_and_other_data = run(figwidth, color_values, track_names, track_type, \
					 bedtrack, bedfile, bedtype, name,annotate_bed, \
		 			 geneid, chrom,start, stop, refseqid, strand, \
		 		 	 bigwignames, fontsize, shade_by_bed)
		# print(figwidth, color_values, track_names, track_type, \
		# 	 bedtrack, bedfile, bedtype, name,annotate_bed, \
		#  	 geneid, chrom,start, stop, refseqid, strand, \
		#  	 bigwignames, fontsize, shade_by_bed)
		return JsonResponse(image_name_and_other_data, safe=False)
	except Exception as e:
		exc_type, exc_obj, exc_tb = sys.exc_info()
		fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
		# print('')

src/main_project/templates/main_project/choose_bam_file.html
{% extends 'base.html' %}
{% load static %}

{% block header_extra_html_css %}
<!-- nothing here -->
{% endblock %}

{% block content %}

  <section id="select-img-body">
    <div class="container select-img-container">
        <div class="row">
            <div class="col-sm-12">
              <div class="slect-box-img-title">
                    <p class="select-box-img-title">Select Experiment(s)</p>
                    <p class="select-box-img-subtitle">human - hg38 build</p>
              </div>
              <div class="col-sm-4 select-img-box1 all-box-same-class">
                <i class="far fa-circle select-img-circle"></i>
                <img data-file="jurkat_all.bam" src="{%  static 'main_design/img/choose_bam_file/jurkat_all.bam.png' %}" class="select-img-src1">

              </div>  
            </div>
            <div class="col-sm-12">
               <div class="slect-box-img-title">
                    <p class="select-box-img-subtitle2">mouse - mm10 build</p>
              </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="GCliPP_cd8_merged.bam" src="{%  static 'main_design/img/choose_bam_file/GCliPP_cd8_merged.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="GCliPP_everything.bam" src="{%  static 'main_design/img/choose_bam_file/GCliPP_everything.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="GCliPP_minus_merged.bam" src="{%  static 'main_design/img/choose_bam_file/GCliPP_minus_merged.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="GCliPP_plus_merged.bam" src="{%  static 'main_design/img/choose_bam_file/GCliPP_plus_merged.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="GCliPP_th2_merged.bam" src="{%  static 'main_design/img/choose_bam_file/GCliPP_th2_merged.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="Loeb_ko_sorted.bam" src="{%  static 'main_design/img/choose_bam_file/Loeb_ko_sorted.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="Loeb_wt_sorted.bam" src="{%  static 'main_design/img/choose_bam_file/Loeb_wt_sorted.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="miR15-16_cKO_RNAseq.bam" src="{%  static 'main_design/img/choose_bam_file/miR15-16_cKO_RNAseq.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="miR15-16_FL_RNAseq.bam" src="{%  static 'main_design/img/choose_bam_file/miR15-16_FL_RNAseq.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="miR29_KO_Th17.bam" src="{%  static 'main_design/img/choose_bam_file/miR29_KO_Th17.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="miR29_WT_All.bam" src="{%  static 'main_design/img/choose_bam_file/miR29_WT_All.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="miR29_WT_Th2.bam" src="{%  static 'main_design/img/choose_bam_file/miR29_WT_Th2.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="miR29_WT_Th17.bam" src="{%  static 'main_design/img/choose_bam_file/miR29_WT_Th17.bam.png' %}" class="select-img-src2">
                </div>
                <div class="col-sm-4 select-img-box2 all-box-same-class">
                    <i class="far fa-circle select-img-circle"></i>
                    <img data-file="RNAseq_Th2_stimulated.bam" src="{%  static 'main_design/img/choose_bam_file/RNAseq_Th2_stimulated.bam.png' %}" class="select-img-src2">
                </div>
            </div>
            <div class="col-sm-12">
                  <p class="plot-button-class">Plot</p>
            </div>
        </div>
    </div>
  </section>

{% endblock %}

{% block footer_extra_html_css %}
  <script>
        $(document).ready(function(){
          $('.graphing_dashboard_menu').addClass('active-page')
        })
        var to_send_url  = 'hi'
        
        // mm10/hg38
        

       // var to_send_url = 


        var circleBoxType="";
        var linkaddfinal = "";
        var link = "{% url 'main_project:graphing_dashboard' %}?genome="

        $(".select-img-box1").click(function(){
           $(".select-img-circle",this).toggleClass("far fas");
           $(".select-img-box2 .select-img-circle").removeClass("fas")
           $(".select-img-box2 .select-img-circle").addClass("far")
           $(this).toggleClass("this-box-is-selected")
           $(".select-img-box2").removeClass("this-box-is-selected")
           circleBoxType="hg38&"

        })

        $(".select-img-box2").click(function(){
           $(".select-img-circle",this).toggleClass("far fas");
           $(".select-img-box1 .select-img-circle").removeClass("fas")
           $(".select-img-box1 .select-img-circle").addClass("far")
           $(this).toggleClass("this-box-is-selected")
           $(".select-img-box1").removeClass("this-box-is-selected")
           circleBoxType="mm10&"
        })

        $(".plot-button-class").click(function(){
           console.log(circleBoxType)
           if ($(".all-box-same-class").hasClass("this-box-is-selected")) {
                $('.this-box-is-selected img').each(function() {
                    var mylist = $(this).attr('data-file')
                    var linkaddclick = 'files[]='+mylist
                    linkaddfinal += linkaddclick+'&'
                });
                
            }
            var sendfinallink = link+circleBoxType+linkaddfinal
            window.location.href = sendfinallink
            console.log(sendfinallink)
        })

   </script>
{% endblock %}

src/main_project/templates/main_project/home.html
{% extends 'base.html' %}
{% load static %}

{% block header_extra_html_css %}
<!-- nothing here -->
{% endblock %}

{% block content %}

<section id="dashboard-popup2">
      <p class="close-the-popup2">X</p>
      <img src="" class="dashboard-popup-img2">  
</section>

 <section class="side-row">
    <div class="side-menu-dev">
        <ul class="side-menu-ul">
            <li class="side-menu-circle active-side-menu"><a href="#video-section" class="side-scroll-class one-button-click"><i class="fas fa-circle"></i></a></li>
            <li class="side-menu-circle"><a href="#part-two-section" class="side-scroll-class two-button-click"><i class="fas fa-circle side-menu-circle"></i></a></li>
            <li class="side-menu-circle"><a href="#part-three-section" class="side-scroll-class three-button-click"><i class="fas fa-circle side-menu-circle"></i></a></li>
            <li class="side-menu-circle"><a href="#footer-section" class="side-scroll-class four-button-click"><i class="fas fa-circle side-menu-circle"></i></a></li>
        </ul>
    </div>
  </section>

 <!--          Video section start     -->
  <section id="video-section">
    <div class="top-write-part">
          <p class="video-introducing video-play-with wow fadeIn" data-wow-duration="1.1s" data-wow-delay="1s">Introducing</p>
          <img class="video-img-logo video-play-with wow fadeIn" data-wow-duration="0s" data-wow-delay="2s" src="{%  static 'main_design/img/logo1.png' %}">
          <p class="video-des video-play-with wow fadeIn" data-wow-duration="0s" data-wow-delay="3s">A New Way to Share and Access High Throughput Sequencing Data</p>
          <div class="col-sm-12 the-two-button">
              <div class="col-sm-6">
                  <a class="button-over-video-text" href="#part-two-section-click">Science Behind Thagomizer</a>
              </div>
              <div class="col-sm-6">
                  <a class="button-over-video-text1" href="{% url 'main_project:choose_bam_file' %}">Plot CLIP</a>
              </div>  
          </div>  
          
    </div>
     <div>
        <video  muted loop autoplay src="https://github.com/sskhon-2014/Thagomizer/blob/master/video.mp4?raw=true" id="myVideo">
        </video>
      </div>  

      <div class="content">
        <i class="far fa-play-circle icon-play" id="myBtn"></i>
      </div>
   
      
  </section>
  <!--          Video section end       -->

<!--
    <video id="VideoElement" autoplay loop controls muted   type="video/mp4"></video>

        </video>-->

  <!--          section two start     -->
  <section id="part-two-section">
    <a class="part-two-up" href="#video-section" style="display: none;">Science Behind Thagomizer</a>
    <a class="part-two-down" href="#part-three-section" style="display: none;">Science Behind Thagomizer</a>
    <p id="part-two-section-click">aaaa</p>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="part-two-title-box">
                <p class="part-two-title">GCLiPP (Global Cross-Linking Protein Purification)</p>
                <p class="part-two-subtitle">A Biochemical Technique for detecting RNA Binding Protein Occupancy Transcriptome-Wide</p>
              </div>
              <div class="col-sm-1"></div>  
              <div class="col-sm-10">
                <div class="col-sm-12">
                    <img src="{%  static 'main_design/img/row.png' %}" class="part-two-img1">              
                </div>
                <div class="col-sm-6 img-second-row">
                    <img src="{%  static 'main_design/img/Scroll_Second_Pic_5.png' %}" class="part-two-img5">
                </div>
                <div class="col-sm-6 img-second-row second-text-row-padding">
                    <p class="part-two-des">To identify RNA cis-regulatory elements in an unbiased manner, <a class="color-blue" href="https://ansel.ucsf.edu">Ansel Lab</a> has developed GCLiPP. Using GCLiPP, we identified RBP binding sites in mRNAs of human Jurkat T cells and mouse primary T cells. GCLiPP sequence tags correspond to known RBP binding sites, specifically correlating to abundant cytosolic RBPs. Thagomizer was designed to host these datasets in a format easily accessible to the research community.</p>
                </div>
              </div>  
            </div>
        </div>
    </div>
  </section>
  <!--          section two end     -->
  
  <!--          section three start     -->
  <section id="part-three-section">
    <a class="part-three-up" href="#part-two-section" style="display: none;">Science Behind Thagomizer</a>
    <a class="part-three-down" href="#footer-section" style="display: none;">Science Behind Thagomizer</a>
     <div class="container">
        <div class="row">
           <div class="three-part-text">
            <p class="part-two-subtitle third-row-sub">A Brief Primer on</p>
            <p class="part-two-title three-title-margin">HITS-CLIP</p>
            <p class="part-three-text1">High-Throughput Sequencing of RNA</p>
            <p class="part-three-text2">Isolated by Crosslinking Immunoprecipitation</p>
           </div>  
            <div class="col-sm-12">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <div class="col-sm-3">
                       <img src="{%  static 'main_design/img/111.png' %}" class="part-two-img1">   
                    </div>
                    <div class="col-sm-3">
                        <img src="{%  static 'main_design/img/222.png' %}" class="part-two-img44">   
                    </div>
                    <div class="col-sm-5">
                        <p class="part-three-des"><a class="color-blue" href="https://www.nature.com/articles/nature07488">Licatalosi et al., 2008</a> presents HITS-
                            CLiP as a powerful biochemical technique to interrogate the binding activity of specific RNA
                            Binding Proteins. HITS-CLiP generates a transcriptome-wide map of Protein-RNA binding sites,
                            thus allowing for the elucidation of cis-regulatory elements.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 part-three-row-two">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <div class="col-sm-3">
                       <img src="{%  static 'main_design/img/333.png' %}" class="part-two-img11">   
                    </div>
                    <div class="col-sm-3">
                      <img src="{%  static 'main_design/img/444.png' %}" class="part-two-img22">   
                    </div>
                    <div class="col-sm-5">
                       <img src="{%  static 'main_design/img/55.png' %}" class="part-two-img33">   
                    </div>
                </div>
            </div>
        </div>
     </div>
  </section>
  <!--          section three end     -->
 

{% endblock %}

{% block footer_extra_html_css %}
  <script>
        $(document).ready(function(){
          $('.home_menu').addClass('active-page')
        })
   </script>
  <script src="{%  static 'main_design/js/baguetteBox.js' %}"></script>
  <script>
    baguetteBox.run('.tz-gallery');
  </script>

{% endblock %}

src/main_project/templates/main_project/team.html
{% extends 'base.html' %}
{% load static %}

{% block header_extra_html_css %}
<!-- nothing here -->
{% endblock %}

{% block content %}

    <section id="our-team">
       <div class="container">
          <div class="row">
              <div class="col-sm-12" id="text-area">
                  <p class="wow fadeIn" data-wow-duration="2.1s" data-wow-delay=".5s">Team</p>
                  <h6 class="wow fadeIn" data-wow-duration="2.1s" data-wow-delay=".7s"></h6>
                  <hr class="wow fadeIn" data-wow-duration="2.1s" data-wow-delay=".9s" id="team-line">
              </div>
          </div>
       </div>
    </section>

    <section id="team-number-section">
      <div class="container">
         <div class="row">
             <div class="col-sm-12">
<!--                 <div class="col-sm-4 wow fadeIn" data-wow-duration="2.1s" data-wow-delay=".5s" id="team-img">
                    <img src="{%  static 'main_design/img/team1.png' %}">
                    <p id="team-member-name">J. Renz</p>
                    <hr id="team-member-line">
                    <p id="team-member-des">Enim semper, gravida interdum nullam, pellentesque adipiscing scelerisque vitae dui, magnis platea. Ac sagittis ridiculus Est ac sollicitudin varius integer laoreet morbi porta</p>
                </div> -->
                <div class="col-sm-2"></div>
                <div class="col-sm-4 wow fadeIn" data-wow-duration="2.1s" data-wow-delay=".5s" id="team-img">
                    <img src="{%  static 'main_design/img/DSC04250.JPG' %}">
                    <p id="team-member-name">Shaan Sekhon</p>
                    <hr id="team-member-line">
                    <p id="team-member-des">Undergraduate Student at the University of California, Berkeley</p>
                </div>
                <div class="col-sm-4 wow fadeIn" data-wow-duration="2.1s" data-wow-delay=".5s" id="team-img">
                    <img src="{%  static 'main_design/img/Robin Kageyama, PhD.png' %}">
                    <p id="team-member-name">Robin Kageyama, PhD</p>
                    <hr id="team-member-line">
                    <p id="team-member-des">Data Engineer at Parker Institute for Cancer Immunotherapy</p>
                </div>
             </div>
         </div>
      </div>
    </section>

{% endblock %}

{% block footer_extra_html_css %}
  <script>
        $(document).ready(function(){
          $('.team_menu').addClass('active-page')
        })
   </script>
{% endblock %}